### ISSUE TITLE
可否增加 pangu.js 的支持

### ISSUE THREAD

**Issue by sunbjt** [1-2-3/remark-it#11]
这个模板非常好，基本是平时撰写 Slides 的主力。有时候需要使用中英文混排，需要“盘古之白”。在 docsify 中可以很容易设置，但在 remark 体系不太容易搞定。如果增加这个就太感谢了。

**Comment by 1-2-3** [comment]
说实话这个我自己做完了都没怎么实际用过，因为平时做Slides还是需要跟其他同事合稿或者需要交给别人再改，还是PowerPoint用的多。听到有人用它来做Slides主力真的感觉很神奇。谢谢你的反馈，我试试看能不能集成 pangu.js

**Comment by 1-2-3** [comment]
> 这个模板非常好，基本是平时撰写 Slides 的主力。有时候需要使用中英文混排，需要“盘古之白”。在 docsify 中可以很容易设置，但在 remark 体系不太容易搞定。如果增加这个就太感谢了。

已经把 pangu.js 加进去了，你试试看。

**Comment by sunbjt** [comment]
太棒了，已经测试成功，太完美了！感谢感谢！

**Comment by 1-2-3** [comment]
> 太棒了，已经测试成功，太完美了！感谢感谢！

好的，那我把问题关闭了。听到这个东西能对您有用我也很高兴，不知道您是做哪方面工作的？

**Comment by sunbjt** [comment]
我对 JS 不熟悉，这个问题困扰我好几年了。昨天你的 issue 通知邮件承包了我一天的快乐！
我是从事数据科学工作的，可以参见这里 https://bjt.name/about/

**Comment by 1-2-3** [comment]
> 我对 JS 不熟悉，这个问题困扰我好几年了。昨天你的 issue 通知邮件承包了我一天的快乐！ 我是从事数据科学工作的，可以参见这里 https://bjt.name/about/

哇，您是数据科学方面的大神呀，失敬失敬，以后有数据科学方面的问题多请教您。您有使用方面的问题或者需求请随时提issue。

**Comment by sunbjt** [comment]
您客气！术业有专攻！
