### ISSUE TITLE
关于导出路径

### ISSUE THREAD

**Issue by LittleSaltFish** [1-2-3/remark-it#3]
建议把导出路径用单引号包围，因为文件路径如果包含空格，会被识别错误。
![image](https://user-images.githubusercontent.com/45428395/84917319-bd6f0d00-b0f1-11ea-891b-56fa5eadaf8a.png)
不大会用提交功能，所以在这提issue了  XD
之前那个错别字是这儿，感觉好像没提交上的样子：
![image](https://user-images.githubusercontent.com/45428395/84917516-03c46c00-b0f2-11ea-92e8-e0915ad37dc6.png)

**Comment by 1-2-3** [comment]
非常感谢你的反馈！已修正。
另，试了下路径有空格的情况，只要是从浏览器里面复制粘贴出来的URL本身已经经过了URL ENCODE，即使有空格也没问题。

**Comment by LittleSaltFish** [comment]
emmm 如果直接复制粘贴本地路径，如果带空格的话会报错哦～
