### ISSUE TITLE
code blocks lose their indenting

### ISSUE THREAD

**Issue by geoffreymbrown** [1-2-3/remark-it#4]
I started to experiment with your example by inserting a code block (e.g.)

```python
def foo(bar):
     return bar + 1
```
and was a little surprised that it rendered as

def foo(bar):
return bar+1

I noticed that your code sample on slide 7 also collapses the white space

**Comment by 1-2-3** [comment]
> I started to experiment with your example by inserting a code block (e.g.)
> 
> ```python
> def foo(bar):
>      return bar + 1
> ```
> 
> and was a little surprised that it rendered as
> 
> def foo(bar):
> return bar+1
> 
> I noticed that your code sample on slide 7 also collapses the white space

Is fixed. Thank you for your feedback.
