### ISSUE TITLE
italics in text ?

### ISSUE THREAD

**Issue by geoffreymbrown** [1-2-3/remark-it#5]
I was developing a presentation and found that italics ( *italic text*) don't seem to work.  Is this a feature of the fonts used in  typo css ?   If so, is there an obvious way to change fonts ?

**Comment by 1-2-3** [comment]
The Markdown syntax USES the `asterisk` wrapping text for italics, but it actually generates the `EM` tag, probably a bug of `remarkjs`. You can use the `<i>` tag to wrap sentences that you want to italicize. Such as:

```md
---
# remark it
<i>A slideshow template powered by remarkjs</i>
---
```
