### ISSUE TITLE
16:9比例内容显示不完全

### ISSUE THREAD

**Issue by xlhaw** [1-2-3/remark-it#7]
将示例ppt中window ratio"4:3"从改为 "16:9"后，Border Layout的Y方向的显示变窄，原有内容超出了页面范围，因此下半部分无法正常查看，请问还需要在哪里设置来保证显示内容在页面内。

![S 2021-05-27_16-37-00](https://user-images.githubusercontent.com/28912944/119795352-f7a07b80-bf0a-11eb-81fa-f41436db1d7f.jpg)

![S 2021-05-27_16-37-42](https://user-images.githubusercontent.com/28912944/119795542-274f8380-bf0b-11eb-8a67-7b0dd7d9a200.jpg)

**Comment by 1-2-3** [comment]
`布局举例 · 上下结构` 那页，把上面的那块高度变小一点即可，例如改成 `.height-40`:
```md
.north.height-40[
  .card.noborder.noround.m-0.width-100.height-100[
    .abs-layout[
      .north
    ]
    .img[![](static/parallax2.jpg)]
  ]
]
```

`CSS 卡片` 那页，单纯只是因为改成 16:9 之后纵向高度不足以容纳那么多内容了。您在实际做演示页的时候在纵向上不去放那么多的内容即可。

**Comment by xlhaw** [comment]
感谢及时的解答！我以为更改比例会有类似响应式效果，看来也还得多注意下排版。
